browser=chrome
baseUrl=https://rahulshettyacademy.com/seleniumPractise/
implicitWaitSeconds=5
explicitWaitSeconds=10
db.url=jdbc:mysql://localhost:3306/greenkart_db
db.username=root
db.password=Rootpass@123