name: Enterprise UI-DB Automation Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: greenkart_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
	  
	  
	- name: Set up JDK 21
	      uses: actions/setup-java@v4
	      with:
	        java-version: '21'
	        distribution: 'temurin'
	        cache: maven

    - name: Initialize Database Schema and Data
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot greenkart_db < src/test/resources/init.sql
		
	- name: Run Maven Tests
		  env:
		  REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
	    run: mvn clean test	

 